// console.table({
//     Tugas:"Silahkan Explorasi Metode Metode ini",
//     Tugas_1:"Inisialisai Ulang Array By Index",
//     Tugas_2:"Pahami .push()" ,
//     Tugas_3:"Pahami .pop()",
//     Tugas_4:"Pahami .shift()",
//     Tugas_5:"Pahami .unshift()",
//     Tugas_6:"Pahami .splice()",
//     Tugas_7:"Pahami .slice()",
//     Tugas_8:"Pahami .map()",
//     Tugas_9:"Pahami .forEach()",
//     Tugas_10:"Pahami .indexOf()",
//     Tugas_11:"Pahami .includes()",
//     Tugas_12:"Pahami .concat()",
//     Tugas_13:"Pahami .join()",
//     Tugas_14:"Pahami .reverse()",
//     Tugas_15:"Pahami .sort()",
//     Tugas_16:"Pahami .filter()",
//     Tugas_17:"Pahami .reduce()",
//     Tugas_18:"Pahami .find()",
//     Tugas_19:"Pahami .some()",
//     Tugas_20:"Pahami .every()",
//     Tugas_21:"Pahami .findIndex()",
//     Tugas_22:"Pahami .flat()",
//     Tugas_23:"Pahami .flatMap()",
//     Tugas_24:"Pahami Spread [...buah, ...sayur,]",
//     Tugas_25:"Pahami Destructuring Array",
// })